import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const vazir = Vazirmatn({
  variable: "--font-vazir"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang={process.env.APP_LANG} dir={process.env.APP_DIR}>
      <body className={`${vazir.variable} antialiased`}>
        {children}

        <Script async src="https://cdn.jsdelivr.net/npm/flowbite@2.5.2/dist/flowbite.min.js"></Script>
      </body>
    </html>
  );
}
